events {}
http {
    upstream fraud_engine {
        server app1:8080;
        server app2:8080;
        server app3:8080;
    }

    server {
        listen 80;
        
        # CORS headers for local frontend
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type';

        location / {
            if ($request_method = 'OPTIONS') {
                return 204;
            }
            proxy_pass http://fraud_engine;
        }
    }
}